DROP TABLE IF EXISTS TBL_EXCHANGES;

CREATE TABLE TBL_EXCHANGES (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  currency_from VARCHAR(250) NOT NULL,
  currency_to VARCHAR(250) NOT NULL,
  date_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  base VARCHAR(250) NOT NULL,
  rate NUMBER NOT NULL,
  user_id VARCHAR(250) NOT NULL,
  value_from NUMBER NOT NULL,
  value_to NUMBER NOT NULL
);

-- INSERT INTO TBL_EXCHANGES (currency_from, currency_to, date_time, base, rate, user_id, value_from, value_to) VALUES('BRL','EUR', CURRENT_TIMESTAMP(9),'EUR',2,'JLOPEZ',45,4500);
